run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - revive
    - gocyclo
    - gocognit
    - gofumpt
    - goimports
    - gosec
    - misspell
    - whitespace
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  gofumpt:
    extra-rules: true
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - gosec
        - errcheck
    - path: testdata/
      linters:
        - gocyclo
        - gocognit
        - gosec
        - errcheck
        - unused
